---
# Handlers for security role

- name: restart sshd
  systemd:
    name: ssh  # Ubuntu uses 'ssh' not 'sshd'
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
