jenkins:
  systemMessage: "Cryptograss Project Builder"
  numExecutors: 3
  scmCheckoutRetryCount: 2
  mode: NORMAL
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${JENKINS_ADMIN_PASSWORD}
        - id: reporter
          password: ${JENKINS_REPORTER_PASSWORD}

  authorizationStrategy:
    globalMatrix:
      entries:
      - userOrGroup:
          name: "admin"
          permissions:
          - "Overall/Administer"
      - user:
          name: "reporter"
          permissions:
          - "Job/Build"
          - "Job/Read"
          - "Overall/Read"
      - user:
          name: "anonymous"
          permissions:
          - "Job/Read"
          - "Overall/Read"

  globalNodeProperties:
    - envVars:
        env:
          - key: "NVM_DIR"
            value: "/var/jenkins_home/.nvm"
          - key: "NODE_VERSION"
            value: "23.6.1"
          - key: "SECRETS_DIR"
            value: "/var/jenkins_home/secrets"

jobs:
  - file: /var/jenkins_home/jobs/production.groovy
  - file: /var/jenkins_home/jobs/pull-requests.groovy
  - file: /var/jenkins_home/jobs/fetch-chain-data.groovy
  - file: /var/jenkins_home/jobs/deploy-hunter.groovy
  - file: /var/jenkins_home/jobs/backup-memory-lane.groovy
  - file: /var/jenkins_home/jobs/deploy-status.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "github-token"
            username: "maybelle"
            password: "${GITHUB_TOKEN}"
            description: "GitHub Token"

unclassified:
  location:
    adminAddress: "admin@cryptograss.live"
    url: "https://maybelle.cryptograss.live/"